version: "3.2"
services:
  geth:
    image: "augurproject/dev-pop-geth:core-${AUGUR_CORE_VERSION}"
    ports:
      - "8545:8545"
      - "8546:8546"

  node:
    image: augurproject/augur-node:core-${AUGUR_CORE_VERSION}
    ports:
      - "9001:9001"
    environment:
      - ETHEREUM_HTTP=http://geth:8545
      - ETHEREUM_WS=ws://geth:8546
    depends_on:
      - geth

    entrypoint: ["/app/wait-for-geth.sh", "geth:8545", "--", "/app/docker-entrypoint.sh"]
